// Code generated by hertz generator.

package friends

import (
	"github.com/cloudwego/hertz/pkg/app"
	"videoweb/middleware"
)

func rootMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _friendsMw() []app.HandlerFunc {
	// your code...
	return nil
}

func _listMw() []app.HandlerFunc {
	// your code...
	return []app.HandlerFunc{middleware.AuthMiddleware()}
}
