// Code generated by hertz generator.

package relation

import (
	"context"
	"videoweb/response"
	"videoweb/service"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	relation "videoweb/biz/model/hertz/relation"
)

// Action .
// @router /relation/action [POST]
func Action(ctx context.Context, c *app.RequestContext) {
	var err error
	var req relation.RelationActionReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, response.BadResponse())
		return
	}

	resp, err := service.ActionRelation(ctx, c, &req)
	if err != nil {
		c.JSON(consts.StatusOK, response.BadResponse())
		return
	}

	c.JSON(consts.StatusOK, resp)
}
