// Code generated by hertz generator.

package following

import (
	"context"
	"videoweb/response"
	"videoweb/service"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	following "videoweb/biz/model/hertz/following"
)

// List .
// @router /following/list [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var err error
	var req following.FollowingListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, response.BadResponse())
		return
	}

	resp, err := service.ListFollowing(ctx, c, &req)
	if err != nil {
		c.JSON(consts.StatusOK, response.BadResponse())
		return
	}
	c.JSON(consts.StatusOK, resp)
}
