// Code generated by hertz generator.

package friends

import (
	"context"
	"videoweb/response"
	"videoweb/service"

	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	friends "videoweb/biz/model/hertz/friends"
)

// List .
// @router /friends/list [GET]
func List(ctx context.Context, c *app.RequestContext) {
	var err error
	var req friends.FriendsListReq
	err = c.BindAndValidate(&req)
	if err != nil {
		c.JSON(consts.StatusOK, response.BadResponse())
		return
	}

	resp, err := service.ListFriends(ctx, c, &req)
	if err != nil {
		c.JSON(consts.StatusOK, response.BadResponse())
		return
	}

	c.JSON(consts.StatusOK, resp)
}
