version: "v2.23.0-desktop.1"




services:



  minio:
    container_name: minio
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    restart: always
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data
    network_mode: "bridge"


  mysql:
    container_name: mysqld
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: videoWebsite
    privileged: true
    ports:
      - "3306:3306"
    network_mode: "bridge"





  redis:
    container_name: redis
    image: redis:7.2.3
    restart: always
    ports:
      - "6379:6379"
    network_mode: "bridge"


  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    network_mode: "bridge"

  web:
    build: .
    container_name: web
    depends_on:
      - mysql
      - redis
      - minio
      - rabbitmq
    ports:
      - "8888:8888"
    restart: always
    volumes:
      - C:/Users/zhuang:/usr/local/data
    network_mode: "bridge"

