// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/app/server"
	"videoweb/config"
	"videoweb/database/DB/dao"
	"videoweb/database/cache"
	"videoweb/rabbitmq"
	"videoweb/service/ws"
)

func main() {
	h := server.Default()
	dao.InitDB()
	config.InitMinIoClient()
	cache.InitRedis()
	rabbitmq.LinkRabbitmq()
	register(h)
	go ws.MessageHandler()

	h.StaticFS("/data", &app.FS{
		Root: "usr/local",
	})
	h.Spin()
}
