// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "videoweb/biz/handler"
	"videoweb/service/ws"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
	r.GET("/ws", ws.HandleConnections) //这里搞一个handler（w,r)
}
